out_dir: data/models/baseline/

model_params:
  batch_size: 128
  val_check_interval: 100
  optim:
    # SGD
    params:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    # MultiStepLR
    params:
      gamma: 0.5
      milestones: [4, 8, 12, 13, 14, 15]
  countries_num: 73
  num_workers_per_loader: 6

trainer_params:
  accelerator: gpu
  devices: 1
  max_epochs: 15
  precision: 16
